#ifndef __ERRORS_H__

#define __ERRORS_H__

#define EXIT_SUCCESS 0
#define ERR_MEM_ALLOC 1
#define ERR_ACTION 2
#define ERR_INPUT_ROWS 3
#define ERR_INPUT_COLUMNS 4
#define ERR_INPUT_NON_ZERO 5
#define ERR_INPUT_ELEM 6
#define ERR_INPUT_PRINT_METHOD 7
#define ERR_MATRIX_NOT_ALLOCATED 8
#define ERR_DIFF_MATRIX_SIZE 9

#endif // __ERRORS_H__
